waiting for review.....
mbabaliiryn/Weather_App pull request #1
Opened 2020-07-29 13:47 UTC by mbabaliiryn

2020-08-18 19:39 UTC, bellom commented
> Weather App that allows users to search for the weather results, day, date and country of any city allover the world

I think you need to write the tasks carried out to build the app not what the app can do, ok?
example; 
![image](https://user-images.githubusercontent.com/31897434/90557715-dc8e2780-e192-11ea-902a-531834f4a342.png)

kindly update this, thanks.

2020-08-18 20:04 UTC, bellom requested changes
## Hi @mbabaliiryn  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**1. The app is not working properly on my local machine, could this be from end 🤔 ;**
![image](https://user-images.githubusercontent.com/31897434/90559922-40feb600-e196-11ea-903d-5edf66deed01.png)

**2. Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-19 11:22 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @mbabaliiryn good job working on this so far :+1: a lot of the corrections from the previous review has been addressed but you skipped the readme,  your live link still points to your Todo project :slightly_smiling_face: 

- Make the temperature switch button display result on click, currently what happens is I have to switch temperature then do a new search before I see results in that temperature. 
![see](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png)

- There be a change in the appearance for every search 
![see](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png)

- When I search for a location that does not exist nothing shows up at all, you need to give the user feedback that this location does not exist.. 

- Also, try to fix the linter errors, currently, it is not passing :slightly_smiling_face: 

**Please make changes and request for another review** 

PS: You did really good with the UI design 

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-08-20 18:40 UTC, uryelah commented on webpack.config.js
> +module.exports = {
- [ ] Add dev server with a specified contentBase to your config, otherwise, it won't run start on some systems.
```
devServer: {
    contentBase: './dist',
  },
```

2020-08-20 18:41 UTC, uryelah commented on src/styles/main.scss
> +#city-form {
- [ ] Keep CSS best practices, avoid using ids as selectors, prefer classes.

2020-08-20 18:43 UTC, uryelah commented on src/util.js
> +label.className = 'switch';
- [ ] Add some text to your switch label, otherwise, it's not clear to the user what it does.

2020-08-21 06:09 UTC, closed without merging